# Generated by Django 2.1.7 on 2019-03-14 08:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='send_to',
            field=models.CharField(default=datetime.datetime(2019, 3, 14, 8, 15, 23, 960659, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
    ]
