# Generated by Django 2.1.5 on 2019-03-14 09:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_send_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time_send',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 3, 14, 9, 56, 38, 786814, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
