# Generated by Django 2.1.5 on 2019-03-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date_travel',
            field=models.DateTimeField(max_length=10),
        ),
    ]
