# Generated by Django 2.1.5 on 2019-03-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0002_auto_20190314_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date_travel',
            field=models.TextField(max_length=10),
        ),
    ]
